#!/bin/sh

./esr_parser.py georgia @GE
./esr_parser.py kazakhstan @KZ
./esr_parser.py kyrgyzstan @KG
./esr_parser.py tajikistan @TJ
./esr_parser.py turkmenistan @TM
./esr_parser.py uzbekistan @UZ
./esr_parser.py azerbaijan @AZ
./esr_parser.py armenia @AM

./esr_parser.py estonia @EE
./esr_parser.py latvia @LV
./esr_parser.py lithuania @LT
./esr_parser.py moldova @MD

./esr_parser.py minsk @BY-MI
./esr_parser.py mogilyov @BY-MA
./esr_parser.py grodno @BY-HR
./esr_parser.py gomel @BY-HO
./esr_parser.py vitebsk @BY-VI
./esr_parser.py brest @BY-BR

./esr_parser.py adygeya @RU-AD
./esr_parser.py altayskiy @RU-ALT
./esr_parser.py amur @RU-AMU
./esr_parser.py arkhan @RU-ARK
./esr_parser.py astrakhan @RU-AST
./esr_parser.py bashkir @RU-BA
./esr_parser.py belgorod @RU-BEL
./esr_parser.py bryansk @RU-BRY
./esr_parser.py buryat @RU-BU
./esr_parser.py chechen @RU-CE
./esr_parser.py chel @RU-CHE
./esr_parser.py chuvash @RU-CU
./esr_parser.py dagestan @RU-DA
./esr_parser.py evrey @RU-YEV
./esr_parser.py ingush @RU-IN
./esr_parser.py irkutsk @RU-IRK
./esr_parser.py ivanov @RU-IVA
./esr_parser.py kabardin @RU-KB
./esr_parser.py kalinin @RU-KGD
./esr_parser.py kalmyk @RU-KL
./esr_parser.py kaluzh @RU-KLU
./esr_parser.py karach @RU-KC
./esr_parser.py karel @RU-KR
./esr_parser.py kemerovo @RU-KEM
./esr_parser.py khabar @RU-KHA
./esr_parser.py khakas @RU-KK
./esr_parser.py khanty @RU-KHM
./esr_parser.py kirov @RU-KIR
./esr_parser.py komi @RU-KO
./esr_parser.py kostrom @RU-KOS
./esr_parser.py krasnodar @RU-KDA
./esr_parser.py krasnoyarsk @RU-KYA
./esr_parser.py kurgan @RU-KGN
./esr_parser.py kursk @RU-KRS
./esr_parser.py leningrad @RU-LEN
./esr_parser.py lipetsk @RU-LIP
./esr_parser.py mariyel @RU-ME
./esr_parser.py mordov @RU-MO
./esr_parser.py mosobl @RU-MOS
./esr_parser.py murmansk @RU-MUR
./esr_parser.py nizhegorod @RU-NIZ
./esr_parser.py novgorod @RU-NGR
./esr_parser.py novosib @RU-NVS
./esr_parser.py omsk @RU-OMS
./esr_parser.py orenburg @RU-ORE
./esr_parser.py orlovsk @RU-ORL
./esr_parser.py osetiya @RU-SE
./esr_parser.py penz @RU-PNZ
./esr_parser.py perm @RU-PER
./esr_parser.py prim @RU-PRI
./esr_parser.py pskov @RU-PSK
./esr_parser.py rostov @RU-ROS
./esr_parser.py ryazan @RU-RYA
./esr_parser.py sakhalin @RU-SAK
./esr_parser.py samar @RU-SAM
./esr_parser.py saratov @RU-SAR
./esr_parser.py smol @RU-SMO
./esr_parser.py stavrop @RU-STA
./esr_parser.py sverdl @RU-SVE
./esr_parser.py tambov @RU-TAM
./esr_parser.py tatar @RU-TA
./esr_parser.py tomsk @RU-TOM
./esr_parser.py tul @RU-TUL
./esr_parser.py tumen @RU-TYU
./esr_parser.py tver @RU-TVE
./esr_parser.py udmurt @RU-UD
./esr_parser.py ulyan @RU-ULY
./esr_parser.py vladimir @RU-VLA
./esr_parser.py volgograd @RU-VGG
./esr_parser.py vologda @RU-VLG
./esr_parser.py voronezh @RU-VOR
./esr_parser.py yakut @RU-SA
./esr_parser.py yamal @RU-YAN
./esr_parser.py yarosl @RU-YAR
./esr_parser.py zabaikal @RU-ZAB

./esr_parser.py kiev @UA-32
./esr_parser.py zhitomir @UA-18
./esr_parser.py cherkassy @UA-71
./esr_parser.py poltava @UA-53
./esr_parser.py chernigov @UA-74
./esr_parser.py sumy @UA-59
./esr_parser.py vinnitsa @UA-05
./esr_parser.py khmelnitsky @UA-68
./esr_parser.py chernovtsy @UA-77
./esr_parser.py rovno @UA-56
./esr_parser.py ternopol @UA-61
./esr_parser.py lvov @UA-46
./esr_parser.py volynsk @UA-07
./esr_parser.py ivanofrank @UA-26
./esr_parser.py zakarpatskaya @UA-21
./esr_parser.py odessa @UA-51
./esr_parser.py nikolaev @UA-48
./esr_parser.py kirovograd @UA-35
./esr_parser.py dnepropetrovsk @UA-12
./esr_parser.py kherson @UA-65
./esr_parser.py zaporozh @UA-23
./esr_parser.py kharkov @UA-63
./esr_parser.py lugansk @UA-09
./esr_parser.py donetsk @UA-14
./esr_parser.py crimea @UA-43
